[package]
name = "generator"
version = "0.1.0"
authors = ["Aphek <bilkow@tutanota.com>"]
edition = "2021"
publish = false

[dependencies]
bindgen = "0.68.1"
lazy_static = "1.4"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
