/* automatically generated by rust-bindgen 0.68.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

extern "C" {
    pub fn ksceKernelMemcpyFromUser(
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelProcMemcpyFromUser(
        pid: SceUID,
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelMemcpyToUser(
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelProcMemcpyToUser(
        pid: SceUID,
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelMemcpyToUserRo(
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelMemcpyToUserRx(
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelProcMemcpyToUserRx(
        pid: SceUID,
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelStrncpyFromUser(
        dst: *mut crate::ctypes::c_char,
        src: *const crate::ctypes::c_char,
        len: SceSize,
    ) -> SceSSize;
}
extern "C" {
    pub fn ksceKernelProcStrncpyFromUser(
        pid: SceUID,
        dst: *mut crate::ctypes::c_char,
        src: *const crate::ctypes::c_char,
        len: SceSize,
    ) -> SceSSize;
}
extern "C" {
    pub fn ksceKernelStrncpyToUser(
        dst: *mut crate::ctypes::c_char,
        src: *const crate::ctypes::c_char,
        len: SceSize,
    ) -> SceSSize;
}
extern "C" {
    pub fn ksceKernelProcStrncpyToUser(
        pid: SceUID,
        dst: *mut crate::ctypes::c_char,
        src: *const crate::ctypes::c_char,
        len: SceSize,
    ) -> SceSSize;
}
extern "C" {
    pub fn ksceKernelStrnlenUser(s: *const crate::ctypes::c_char, n: SceSize) -> SceSize;
}
extern "C" {
    pub fn ksceKernelProcStrnlenUser(
        pid: SceUID,
        s: *const crate::ctypes::c_char,
        n: SceSize,
    ) -> SceSSize;
}
extern "C" {
    pub fn ksceKernelUserMemcpy(
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelProcUserMemcpy(
        pid: SceUID,
        dst: *mut crate::ctypes::c_void,
        src: *const crate::ctypes::c_void,
        len: SceSize,
    ) -> crate::ctypes::c_int;
}
