/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;
#[allow(unused_imports)]
use crate::vitasdk::build_utils::*;

extern "C" {
    pub fn ksceKernelVAtoPA(
        va: *const crate::ctypes::c_void,
        pa: *mut usize,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelVARangeToPAVector(
        va_range: *const SceKernelVARange,
        pa_vector: *mut SceKernelPAVector,
    ) -> crate::ctypes::c_int;
}
#[repr(C)]
pub struct SceKernelProcessContext {
    pub TTBR1: SceUInt32,
    pub DACR: SceUInt32,
    pub CONTEXTIDR: SceUInt32,
}
extern "C" {
    pub fn ksceKernelGetPidContext(
        pid: SceUID,
        ctx: *mut *mut SceKernelProcessContext,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelSwitchVmaForPid(pid: SceUID) -> crate::ctypes::c_int;
}
