/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

extern "C" {
    pub fn kscePUIDOpenByGUID(pid: SceUID, guid: SceUID) -> SceUID;
}
extern "C" {
    pub fn kscePUIDClose(pid: SceUID, puid: SceUID) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn kscePUIDtoGUID(pid: SceUID, puid: SceUID) -> SceUID;
}
