/* automatically generated by rust-bindgen 0.65.1 */

pub mod SceAudioInErrorCode {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_AUDIO_IN_ERROR_FATAL: Type = 2149974272;
    pub const SCE_AUDIO_IN_ERROR_INVALID_PORT: Type = 2149974273;
    pub const SCE_AUDIO_IN_ERROR_INVALID_SIZE: Type = 2149974274;
    pub const SCE_AUDIO_IN_ERROR_INVALID_SAMPLE_FREQ: Type = 2149974275;
    pub const SCE_AUDIO_IN_ERROR_INVALID_PORT_TYPE: Type = 2149974276;
    pub const SCE_AUDIO_IN_ERROR_INVALID_POINTER: Type = 2149974277;
    pub const SCE_AUDIO_IN_ERROR_INVALID_PORT_PARAM: Type = 2149974278;
    pub const SCE_AUDIO_IN_ERROR_PORT_FULL: Type = 2149974279;
    pub const SCE_AUDIO_IN_ERROR_OUT_OF_MEMORY: Type = 2149974280;
    pub const SCE_AUDIO_IN_ERROR_NOT_OPENED: Type = 2149974281;
    pub const SCE_AUDIO_IN_ERROR_BUSY: Type = 2149974282;
    pub const SCE_AUDIO_IN_ERROR_INVALID_PARAMETER: Type = 2149974283;
}
pub mod SceAudioInPortType {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_AUDIO_IN_PORT_TYPE_VOICE: Type = 0;
    pub const SCE_AUDIO_IN_PORT_TYPE_RAW: Type = 2;
}
pub mod SceAudioInParam {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_AUDIO_IN_PARAM_FORMAT_S16_MONO: Type = 0;
    pub const SCE_AUDIO_IN_GETSTATUS_MUTE: Type = 1;
}
extern "C" {
    pub fn sceAudioInOpenPort(
        portType: SceAudioInPortType::Type,
        grain: crate::ctypes::c_int,
        freq: crate::ctypes::c_int,
        param: SceAudioInParam::Type,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceAudioInReleasePort(port: crate::ctypes::c_int) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceAudioInInput(
        port: crate::ctypes::c_int,
        destPtr: *mut crate::ctypes::c_void,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceAudioInGetAdopt(portType: SceAudioInPortType::Type) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceAudioInGetStatus(select: crate::ctypes::c_int) -> crate::ctypes::c_int;
}
