/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2common::display::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::vitasdk::build_utils::*;

extern "C" {
    pub fn sceDisplaySetFrameBuf(
        pParam: *const SceDisplayFrameBuf,
        sync: SceDisplaySetBufSync::Type,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayGetFrameBuf(
        pParam: *mut SceDisplayFrameBuf,
        sync: SceDisplaySetBufSync::Type,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayGetPrimaryHead() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayGetRefreshRate(pFps: *mut f32) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayGetMaximumFrameBufResolution(
        width: *mut crate::ctypes::c_int,
        height: *mut crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayGetVcount() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayGetVcountInternal(display: crate::ctypes::c_int) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayWaitVblankStart() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayWaitVblankStartCB() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayWaitVblankStartMulti(vcount: crate::ctypes::c_uint) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayWaitVblankStartMultiCB(vcount: crate::ctypes::c_uint) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayWaitSetFrameBuf() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayWaitSetFrameBufCB() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayWaitSetFrameBufMulti(vcount: crate::ctypes::c_uint) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayWaitSetFrameBufMultiCB(vcount: crate::ctypes::c_uint) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayRegisterVblankStartCallback(uid: SceUID) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceDisplayUnregisterVblankStartCallback(uid: SceUID) -> crate::ctypes::c_int;
}
