/* automatically generated by rust-bindgen 0.58.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;

pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x0: u32 = 0;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x1: u32 = 1;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x2: u32 = 2;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x4: u32 = 4;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x8: u32 = 8;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x10: u32 = 16;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x20: u32 = 32;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x100: u32 = 256;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x200: u32 = 512;
pub const SCE_SBL_DMAC5_COMMAND_BASIC_0x300: u32 = 768;
pub const SCE_SBL_DMAC5_COMMAND_MEMCPY: u32 = 0;
pub const SCE_SBL_DMAC5_COMMAND_MEMSET: u32 = 12;
pub const SCE_SBL_DMAC5_COMMAND_RNG: u32 = 4;
pub const SCE_SBL_DMAC5_COMMAND_SHA: u32 = 3;
pub const SCE_SBL_DMAC5_COMMAND_HASH_BIT_SIZE_SHA1: u32 = 0;
pub const SCE_SBL_DMAC5_COMMAND_HASH_BIT_SIZE_SHA224: u32 = 8;
pub const SCE_SBL_DMAC5_COMMAND_HASH_BIT_SIZE_SHA256: u32 = 16;
pub const SCE_SBL_DMAC5_COMMAND_SHA1: u32 = 3;
pub const SCE_SBL_DMAC5_COMMAND_SHA224: u32 = 11;
pub const SCE_SBL_DMAC5_COMMAND_SHA256: u32 = 19;
pub const SCE_SBL_DMAC5_COMMAND_HMAC_SHA: u32 = 32;
pub const SCE_SBL_DMAC5_COMMAND_HMAC_SHA1: u32 = 35;
pub const SCE_SBL_DMAC5_COMMAND_HMAC_SHA224: u32 = 43;
pub const SCE_SBL_DMAC5_COMMAND_HMAC_SHA256: u32 = 51;
pub const SCE_SBL_DMAC5_COMMAND_AES_BIT_SIZE_128: u32 = 256;
pub const SCE_SBL_DMAC5_COMMAND_AES_BIT_SIZE_192: u32 = 512;
pub const SCE_SBL_DMAC5_COMMAND_AES_BIT_SIZE_256: u32 = 768;
pub const SCE_SBL_DMAC5_COMMAND_AES_ECB_ENC: u32 = 1;
pub const SCE_SBL_DMAC5_COMMAND_AES_ECB_DEC: u32 = 2;
pub const SCE_SBL_DMAC5_COMMAND_AES_128_ECB_ENC: u32 = 257;
pub const SCE_SBL_DMAC5_COMMAND_AES_128_ECB_DEC: u32 = 258;
pub const SCE_SBL_DMAC5_COMMAND_AES_192_ECB_ENC: u32 = 513;
pub const SCE_SBL_DMAC5_COMMAND_AES_192_ECB_DEC: u32 = 514;
pub const SCE_SBL_DMAC5_COMMAND_AES_256_ECB_ENC: u32 = 769;
pub const SCE_SBL_DMAC5_COMMAND_AES_256_ECB_DEC: u32 = 770;
pub const SCE_SBL_DMAC5_COMMAND_AES_CBC: u32 = 8;
pub const SCE_SBL_DMAC5_COMMAND_AES_CBC_ENC: u32 = 9;
pub const SCE_SBL_DMAC5_COMMAND_AES_CBC_DEC: u32 = 10;
pub const SCE_SBL_DMAC5_COMMAND_AES_128_CBC_ENC: u32 = 265;
pub const SCE_SBL_DMAC5_COMMAND_AES_128_CBC_DEC: u32 = 266;
pub const SCE_SBL_DMAC5_COMMAND_AES_192_CBC_ENC: u32 = 521;
pub const SCE_SBL_DMAC5_COMMAND_AES_192_CBC_DEC: u32 = 522;
pub const SCE_SBL_DMAC5_COMMAND_AES_256_CBC_ENC: u32 = 777;
pub const SCE_SBL_DMAC5_COMMAND_AES_256_CBC_DEC: u32 = 778;
pub const SCE_SBL_DMAC5_COMMAND_AES_CTR: u32 = 16;
pub const SCE_SBL_DMAC5_COMMAND_AES_CTR_ENC: u32 = 17;
pub const SCE_SBL_DMAC5_COMMAND_AES_CTR_DEC: u32 = 18;
pub const SCE_SBL_DMAC5_COMMAND_AES_128_CTR_ENC: u32 = 273;
pub const SCE_SBL_DMAC5_COMMAND_AES_128_CTR_DEC: u32 = 274;
pub const SCE_SBL_DMAC5_COMMAND_AES_192_CTR_ENC: u32 = 529;
pub const SCE_SBL_DMAC5_COMMAND_AES_192_CTR_DEC: u32 = 530;
pub const SCE_SBL_DMAC5_COMMAND_AES_256_CTR_ENC: u32 = 785;
pub const SCE_SBL_DMAC5_COMMAND_AES_256_CTR_DEC: u32 = 786;
pub const SCE_SBL_DMAC5_COMMAND_AES_CMAC: u32 = 59;
pub const SCE_SBL_DMAC5_COMMAND_AES_128_CMAC: u32 = 315;
pub const SCE_SBL_DMAC5_COMMAND_AES_192_CMAC: u32 = 571;
pub const SCE_SBL_DMAC5_COMMAND_AES_256_CMAC: u32 = 827;
#[repr(C)]
pub struct SceDmac5EncDecParam {
    pub src: *const crate::ctypes::c_void,
    pub dst: *mut crate::ctypes::c_void,
    pub size: SceSize,
    pub key: *const crate::ctypes::c_void,
    pub key_bit_size: SceSize,
    pub iv: *mut crate::ctypes::c_void,
}
extern "C" {
    pub fn sceSblDmac5EncDec(
        param: *mut SceDmac5EncDecParam,
        command: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
