/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2::common_dialog::*;
#[allow(unused_imports)]
use crate::psp2::libime::*;
#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;

pub const SCE_IME_DIALOG_MAX_TITLE_LENGTH: u32 = 128;
pub const SCE_IME_DIALOG_MAX_TEXT_LENGTH: u32 = 2048;
pub mod SceImeDialogErrorCode {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_IME_DIALOG_ERROR_PARAM: Type = 2148540417;
    pub const SCE_IME_DIALOG_ERROR_INTERNAL: Type = 2148540418;
    pub const SCE_IME_DIALOG_ERROR_INVALID_DIALOG_MODE: Type = 2148540419;
    pub const SCE_IME_DIALOG_ERROR_INVALID_TEXT_BOX_MODE: Type = 2148540420;
    pub const SCE_IME_DIALOG_ERROR_INVALID_TITLE: Type = 2148540421;
}
pub use self::SceImeDialogErrorCode::Type as SceImeDialogError;
pub mod SceImeDialogDialogMode {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_IME_DIALOG_DIALOG_MODE_DEFAULT: Type = 0;
    pub const SCE_IME_DIALOG_DIALOG_MODE_WITH_CANCEL: Type = 1;
}
pub mod SceImeDialogTextboxMode {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_IME_DIALOG_TEXTBOX_MODE_DEFAULT: Type = 0;
    pub const SCE_IME_DIALOG_TEXTBOX_MODE_PASSWORD: Type = 1;
    pub const SCE_IME_DIALOG_TEXTBOX_MODE_WITH_CLEAR: Type = 2;
}
pub mod SceImeDialogButton {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_IME_DIALOG_BUTTON_NONE: Type = 0;
    pub const SCE_IME_DIALOG_BUTTON_CLOSE: Type = 1;
    pub const SCE_IME_DIALOG_BUTTON_ENTER: Type = 2;
}
#[repr(C)]
pub struct SceImeDialogParam {
    pub sdkVersion: SceUInt32,
    pub inputMethod: SceUInt32,
    pub supportedLanguages: SceUInt64,
    pub languagesForced: SceBool,
    pub type_: SceUInt32,
    pub option: SceUInt32,
    pub filter: SceImeTextFilter,
    pub dialogMode: SceUInt32,
    pub textBoxMode: SceUInt32,
    pub title: *const SceWChar16,
    pub maxTextLength: SceUInt32,
    pub initialText: *mut SceWChar16,
    pub inputTextBuffer: *mut SceWChar16,
    pub commonParam: SceCommonDialogParam,
    pub enterLabel: SceUChar8,
    pub reserved: [SceChar8; 35usize],
}
#[repr(C)]
pub struct SceImeDialogResult {
    pub result: SceInt32,
    pub button: SceInt32,
    pub reserved: [SceChar8; 28usize],
}
extern "C" {
    pub fn sceImeDialogInit(param: *const SceImeDialogParam) -> SceInt32;
}
extern "C" {
    pub fn sceImeDialogGetStatus() -> SceCommonDialogStatus::Type;
}
extern "C" {
    pub fn sceImeDialogAbort() -> SceInt32;
}
extern "C" {
    pub fn sceImeDialogGetResult(result: *mut SceImeDialogResult) -> SceInt32;
}
extern "C" {
    pub fn sceImeDialogTerm() -> SceInt32;
}
