/* automatically generated by rust-bindgen 0.58.1 */

extern "C" {
    pub fn sceMtpIfStartDriver(flags: crate::ctypes::c_int) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceMtpIfStopDriver(flags: crate::ctypes::c_int) -> crate::ctypes::c_int;
}
