/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MusicExportParam {
    pub reserved: [crate::ctypes::c_char; 128usize],
}
extern "C" {
    pub fn sceMusicExportFromFile(
        path: *const crate::ctypes::c_char,
        param: *const MusicExportParam,
        workingMemory: *mut crate::ctypes::c_void,
        cancelCb: *mut crate::ctypes::c_void,
        progress: ::core::option::Option<
            unsafe extern "C" fn(arg1: *mut crate::ctypes::c_void, arg2: crate::ctypes::c_int),
        >,
        user: *mut crate::ctypes::c_void,
        outPath: *mut crate::ctypes::c_char,
        outPathSize: SceSize,
    ) -> crate::ctypes::c_int;
}
