/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;

pub mod SceRazorGpuLiveMetricsGroup {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_RAZOR_GPU_LIVE_METRICS_GROUP_PBUFFER_USAGE: Type = 0;
    pub const SCE_RAZOR_GPU_LIVE_METRICS_GROUP_OVERVIEW_1: Type = 1;
    pub const SCE_RAZOR_GPU_LIVE_METRICS_GROUP_OVERVIEW_2: Type = 2;
    pub const SCE_RAZOR_GPU_LIVE_METRICS_GROUP_OVERVIEW_3: Type = 3;
}
pub mod SceRazorLiveTraceMetricEntryType {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_ENTRY_TYPE_JOB: Type = 0;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_ENTRY_TYPE_PARAMETER_BUFFER: Type = 1;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_ENTRY_TYPE_FRAME: Type = 2;
}
pub mod SceRazorLiveTraceMetricJobType {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_FIRMWARE: Type = 0;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_VERTEX1: Type = 1;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_FRAGMENT1: Type = 2;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_VERTEX2: Type = 3;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_FRAGMENT2: Type = 4;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_VERTEX3: Type = 5;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_FRAGMENT3: Type = 6;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_VERTEX0: Type = 7;
    pub const SCE_RAZOR_LIVE_TRACE_METRIC_JOB_TYPE_FRAGMENT0: Type = 8;
}
#[repr(C)]
pub struct SceRazorGpuLiveResultInfo {
    pub result_data: *mut crate::ctypes::c_void,
    pub entry_count: SceSize,
    pub overflow_count: SceSize,
    pub buffer_size: SceSize,
    pub start_time: u64,
    pub end_time: u64,
    pub metric_group: u32,
    pub reserved: crate::ctypes::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryHeader {
    pub entry_size: u16,
    pub entry_type: u16,
    pub reserved: crate::ctypes::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryJobVertexValues1 {
    pub usse_vertex_processing_percent: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryJobFragmentValues1 {
    pub usse_fragment_processing_percent: f32,
    pub usse_dependent_texture_reads_percent: f32,
    pub usse_non_dependent_texture_reads_percent: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryJobVertexValues2 {
    pub vdm_primitives_input_num: u32,
    pub mte_primitives_output_num: u32,
    pub vdm_vertices_input_num: u32,
    pub mte_vertices_output_num: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryJobFragmentValues2 {
    pub rasterized_pixels_before_hsr_num: u32,
    pub rasterized_output_pixels_num: u32,
    pub rasterized_output_samples_num: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryJobVertexValues3 {
    pub tiling_accelerated_mem_writes: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryJobFragmentValues3 {
    pub isp_parameter_fetches_mem_reads: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryJobValues {
    pub vertex_values_type1: SceRazorGpuLiveEntryJobVertexValues1,
    pub fragment_values_type1: SceRazorGpuLiveEntryJobFragmentValues1,
    pub vertex_values_type2: SceRazorGpuLiveEntryJobVertexValues2,
    pub fragment_values_type2: SceRazorGpuLiveEntryJobFragmentValues2,
    pub vertex_values_type3: SceRazorGpuLiveEntryJobVertexValues3,
    pub fragment_values_type3: SceRazorGpuLiveEntryJobFragmentValues3,
    pub reserved: [crate::ctypes::c_int; 8usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryJob {
    pub header: SceRazorGpuLiveEntryHeader,
    pub start_time: u64,
    pub end_time: u64,
    pub type_: u8,
    pub core: i8,
    pub scene_index: u16,
    pub frame_number: u32,
    pub job_values: SceRazorGpuLiveEntryJobValues,
    pub process_id: u32,
    pub unk: crate::ctypes::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryParameterBuffer {
    pub header: SceRazorGpuLiveEntryHeader,
    pub peak_usage_timestamp: u64,
    pub peak_usage_value: u32,
    pub partial_render: u8,
    pub vertex_job_paused: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceRazorGpuLiveEntryFrame {
    pub header: SceRazorGpuLiveEntryHeader,
    pub start_time: u64,
    pub duration: u32,
    pub frame_number: u32,
    pub gpu_activity_duration_time: u32,
    pub reserved: crate::ctypes::c_int,
}
extern "C" {
    pub fn sceRazorGpuLiveSetMetricsGroup(metrics: u32) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRazorGpuLiveSetBuffer(
        buffer: *mut crate::ctypes::c_void,
        buf_size: SceSize,
        results: *mut SceRazorGpuLiveResultInfo,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRazorGpuLiveStart() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRazorGpuLiveStop() -> crate::ctypes::c_int;
}
