/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;

extern "C" {
    pub fn sceRegMgrGetKeyBin(
        category: *const crate::ctypes::c_char,
        name: *const crate::ctypes::c_char,
        buf: *mut crate::ctypes::c_void,
        size: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrGetKeyInt(
        category: *const crate::ctypes::c_char,
        name: *const crate::ctypes::c_char,
        buf: *mut crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrGetKeyStr(
        category: *const crate::ctypes::c_char,
        name: *const crate::ctypes::c_char,
        buf: *mut crate::ctypes::c_char,
        size: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrSetKeyBin(
        category: *const crate::ctypes::c_char,
        name: *const crate::ctypes::c_char,
        buf: *mut crate::ctypes::c_void,
        size: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrSetKeyInt(
        category: *const crate::ctypes::c_char,
        name: *const crate::ctypes::c_char,
        buf: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrSetKeyStr(
        category: *const crate::ctypes::c_char,
        name: *const crate::ctypes::c_char,
        buf: *mut crate::ctypes::c_char,
        size: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrGetInitVals(
        category: *const crate::ctypes::c_char,
        buf: *mut crate::ctypes::c_char,
        elements_number: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrGetKeys(
        category: *const crate::ctypes::c_char,
        buf: *mut crate::ctypes::c_char,
        elements_number: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrSetKeys(
        category: *const crate::ctypes::c_char,
        buf: *mut crate::ctypes::c_char,
        elements_number: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrSystemParamGetInt(
        id: crate::ctypes::c_int,
        buf: *mut crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrSystemParamGetStr(
        id: crate::ctypes::c_int,
        buf: *mut crate::ctypes::c_char,
        size: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceRegMgrGetRegVersion(
        version: crate::ctypes::c_int,
        buf: *mut crate::ctypes::c_char,
    ) -> crate::ctypes::c_int;
}
