/* automatically generated by rust-bindgen 0.68.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::vitasdk::build_utils::*;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceSqliteMallocMethods {
    pub xMalloc: ::core::option::Option<
        unsafe extern "C" fn(arg1: crate::ctypes::c_int) -> *mut crate::ctypes::c_void,
    >,
    pub xRealloc: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut crate::ctypes::c_void,
            arg2: crate::ctypes::c_int,
        ) -> *mut crate::ctypes::c_void,
    >,
    pub xFree: ::core::option::Option<unsafe extern "C" fn(arg1: *mut crate::ctypes::c_void)>,
}
extern "C" {
    pub fn sceSqliteConfigMallocMethods(
        methods: *mut SceSqliteMallocMethods,
    ) -> crate::ctypes::c_int;
}
