/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;

pub const SCE_UPDATE_MODE_SWU_GUI: u32 = 16;
pub const SCE_UPDATE_MODE_SWU_CUI: u32 = 48;
pub type SceUpdateMode = crate::ctypes::c_char;
extern "C" {
    pub fn sceSblUsGetUpdateMode(mode: *mut SceUpdateMode) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceSblUsSetUpdateMode(mode: SceUpdateMode) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceSblUsVerifyPup(path: *const crate::ctypes::c_char) -> crate::ctypes::c_int;
}
