/* automatically generated by rust-bindgen 0.68.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2common::usbserv::*;

extern "C" {
    pub fn sceUsbServAccessoryActivate() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn sceUsbServAccessoryDeactivate() -> crate::ctypes::c_int;
}
