/* automatically generated by rust-bindgen 0.58.1 */

#[repr(C)]
pub struct SceLibraryEntryTable {
    pub size: u16,
    pub ver: u16,
    pub attr: u16,
    pub funcNum: u16,
    pub varNum: u32,
    pub unkNum: u32,
    pub nid: u32,
    pub name: *const crate::ctypes::c_char,
    pub nids: *const u32,
    pub ents: *mut *const crate::ctypes::c_void,
}
