/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2common::fios2::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

extern "C" {
    pub fn ksceFiosKernelOverlayAdd(
        overlay: *mut SceFiosOverlay,
        outID: *mut SceFiosOverlayID,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceFiosKernelOverlayAddForProcess(
        pid: SceUID,
        overlay: *mut SceFiosOverlay,
        outID: *mut SceFiosOverlayID,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceFiosKernelOverlayRemoveForProcess(
        pid: SceUID,
        id: SceFiosOverlayID,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceFiosKernelOverlayResolveSync(
        pid: SceUID,
        resolveFlag: crate::ctypes::c_int,
        inPath: *const crate::ctypes::c_char,
        outPath: *mut crate::ctypes::c_char,
        maxPath: SceSize,
    ) -> crate::ctypes::c_int;
}
