/* automatically generated by rust-bindgen 0.68.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

extern "C" {
    pub fn ksceIdStorageReadLeaf(
        leafnum: SceSize,
        buf: *mut crate::ctypes::c_void,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceIdStorageWriteLeaf(
        leafnum: SceSize,
        buf: *const crate::ctypes::c_void,
    ) -> crate::ctypes::c_int;
}
