/* automatically generated by rust-bindgen 0.58.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

extern "C" {
    pub fn ksceSblAimgrGetSMI(info: *mut SceUInt32) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrGetProductCode() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsTest() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsTool() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsDEX() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsCEX() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsVITA() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsDolce() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsGenuineVITA() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsGenuineDolce() -> crate::ctypes::c_int;
}
