/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

pub mod SceProductCode {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_PRODUCT_CODE_NONE: Type = 0;
    pub const SCE_PRODUCT_CODE_TEST: Type = 256;
    pub const SCE_PRODUCT_CODE_TOOL: Type = 257;
    pub const SCE_PRODUCT_CODE_DEX: Type = 258;
    pub const SCE_PRODUCT_CODE_CEX_J1: Type = 259;
    pub const SCE_PRODUCT_CODE_CEX_UC2: Type = 260;
    pub const SCE_PRODUCT_CODE_CEX_CEL: Type = 261;
    pub const SCE_PRODUCT_CODE_CEX_KR2: Type = 262;
    pub const SCE_PRODUCT_CODE_CEX_CEK: Type = 263;
    pub const SCE_PRODUCT_CODE_CEX_MX2: Type = 264;
    pub const SCE_PRODUCT_CODE_CEX_AU3: Type = 265;
    pub const SCE_PRODUCT_CODE_CEX_E12: Type = 266;
    pub const SCE_PRODUCT_CODE_CEX_TW1: Type = 267;
    pub const SCE_PRODUCT_CODE_CEX_RU3: Type = 268;
    pub const SCE_PRODUCT_CODE_CEX_CN9: Type = 269;
    pub const SCE_PRODUCT_CODE_CEX_HK5: Type = 270;
    pub const SCE_PRODUCT_CODE_CEX_RSV1: Type = 271;
    pub const SCE_PRODUCT_CODE_CEX_RSV2: Type = 272;
    pub const SCE_PRODUCT_CODE_CEX_RSV3: Type = 273;
}
extern "C" {
    pub fn ksceSblAimgrGetSMI(info: *mut SceUInt32) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrGetProductCode() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrGetProductSubCode() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsTest() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsTool() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsDEX() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsCEX() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsVITA() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsDolce() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsGenuineVITA() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAimgrIsGenuineDolce() -> crate::ctypes::c_int;
}
