/* automatically generated by rust-bindgen 0.58.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

extern "C" {
    pub fn ksceSblAuthMgrClearDmac5Key(
        slot_id: crate::ctypes::c_int,
        val: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceSblAuthMgrSetDmac5Key(
        key: *const crate::ctypes::c_void,
        keylen: SceSize,
        slot_id: crate::ctypes::c_int,
        key_id: crate::ctypes::c_int,
    ) -> crate::ctypes::c_int;
}
