/* automatically generated by rust-bindgen 0.68.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::vitasdk::build_utils::*;

pub mod _bindgen_ty_2 {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_GUID_SYSROOT: Type = 65537;
    pub const SCE_GUID_GUID_ENTRY_HEAP: Type = 65539;
    pub const SCE_GUID_KERNEL_PROCESS_ID: Type = 65541;
    pub const SCE_GUID_KERNEL_ADDRESS_SPACE: Type = 65543;
    pub const SCE_GUID_PART_ROOT: Type = 65545;
    pub const SCE_GUID_KERNEL_HEAP: Type = 65547;
    pub const SCE_GUID_KERNEL_HEAP_UNCACHE: Type = 65549;
    pub const SCE_GUID_PHYMEM_PART_KERNEL: Type = 65551;
    pub const SCE_GUID_PHYMEM_PART_TOOL: Type = 65553;
    pub const SCE_GUID_DUMMY_PROCESS_GAME: Type = 65555;
    pub const SCE_GUID_DUMMY_PROCESS_SYSTEM: Type = 65557;
    pub const SCE_GUID_CLEANER_THREAD: Type = 65559;
    pub const SCE_GUID_IDLE_THREAD_0: Type = 65561;
    pub const SCE_GUID_IDLE_THREAD_1: Type = 65563;
    pub const SCE_GUID_IDLE_THREAD_2: Type = 65565;
    pub const SCE_GUID_IDLE_THREAD_3: Type = 65567;
    pub const SCE_GUID_ALL_PROCESS: Type = 65569;
    pub const SCE_GUID_GLOBAL_WORK_QUEUE: Type = 65571;
    pub const SCE_GUID_THREAD_ID_SYSTEM_ALL: Type = 65573;
    pub const SCE_GUID_THREAD_ID_PROCESS_ALL: Type = 65575;
    pub const SCE_GUID_RESERVED_29: Type = 65577;
    pub const SCE_GUID_KERNEL_HEAP_TOOL: Type = 65579;
    pub const SCE_GUID_RESERVED_2D: Type = 65581;
    pub const SCE_GUID_RESERVED_2F: Type = 65583;
    pub const SCE_GUID_RESERVED_31: Type = 65585;
    pub const SCE_GUID_KERNEL_FIXED_HEAP_16B: Type = 65587;
    pub const SCE_GUID_KERNEL_FIXED_HEAP_32B: Type = 65589;
    pub const SCE_GUID_KERNEL_FIXED_HEAP_48B: Type = 65591;
    pub const SCE_GUID_KERNEL_FIXED_HEAP_64B: Type = 65593;
    pub const SCE_GUID_KERNEL_FIXED_HEAP_128B: Type = 65595;
    pub const SCE_GUID_KERNEL_FIXED_HEAP_256B: Type = 65597;
    pub const SCE_GUID_KERNEL_FIXED_HEAP_512B: Type = 65599;
    pub const SCE_GUID_KERNEL_FIXED_HEAP_L2_OBJECT: Type = 65601;
    pub const SCE_GUID_PART_USER_SHARED: Type = 65603;
    pub const SCE_GUID_PART_IO: Type = 65605;
    pub const SCE_GUID_PART_CDRAM: Type = 65607;
    pub const SCE_GUID_RESERVED_49: Type = 65609;
    pub const SCE_GUID_PART_TMP: Type = 65611;
    pub const SCE_GUID_PART_ROOT_UNCACHE: Type = 65613;
    pub const SCE_GUID_PART_KMP: Type = 65615;
    pub const SCE_GUID_PART_ROOT_UNCACHE_GPU_GAME: Type = 65617;
    pub const SCE_GUID_PART_TMP_FS_GAME: Type = 65619;
    pub const SCE_GUID_PART_ROOT_TOOL: Type = 65621;
    pub const SCE_GUID_PART_ROOT_TOOL_UNCACHE: Type = 65623;
    pub const SCE_GUID_PROCESS_BUDGET_KERNEL: Type = 65625;
    pub const SCE_GUID_PROCESS_BUDGET_SHELL: Type = 65627;
    pub const SCE_GUID_PROCESS_BUDGET_FULL_GAME: Type = 65629;
    pub const SCE_GUID_RESERVED_5F: Type = 65631;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceKernelAddrPair {
    pub addr: u32,
    pub length: u32,
}
#[repr(C)]
pub struct SceKernelVARange {
    pub addr: u32,
    pub size: SceSize,
}
#[repr(C)]
pub struct SceKernelPARange {
    pub addr: u32,
    pub size: SceSize,
}
#[repr(C)]
pub struct SceKernelPAVector {
    pub size: SceSize,
    pub __bindgen_anon_1: SceKernelPAVector__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union SceKernelPAVector__bindgen_ty_1 {
    pub __bindgen_anon_1: SceKernelPAVector__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: SceKernelPAVector__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceKernelPAVector__bindgen_ty_1__bindgen_ty_1 {
    pub ranges_size: u32,
    pub data_in_vector: u32,
    pub count: u32,
    pub ranges: *mut SceKernelPARange,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceKernelPAVector__bindgen_ty_1__bindgen_ty_2 {
    pub list_size: u32,
    pub ret_length: u32,
    pub ret_count: u32,
    pub list: *mut SceKernelAddrPair,
}
pub type SceKernelPaddrList = SceKernelPAVector;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SceSharedSecret {
    pub shared_secret_0: [u8; 16usize],
    pub klicensee: [u8; 16usize],
    pub shared_secret_2: [u8; 16usize],
    pub shared_secret_3_0: u32,
    pub shared_secret_3_1: u32,
    pub shared_secret_3_2: u32,
    pub shared_secret_3_3: u32,
}
#[repr(C)]
pub struct SceSelfAuthInfo {
    pub program_authority_id: SceUInt64,
    pub padding: [u8; 8usize],
    pub capability: [u8; 32usize],
    pub attribute: [u8; 32usize],
    pub secret: SceSharedSecret,
}
#[repr(C)]
pub struct SceAuthInfo {
    pub unk_0x00: SceUInt32,
    pub self_type: SceUInt32,
    pub request: SceSelfAuthInfo,
    pub response: SceSelfAuthInfo,
    pub media_type: SceUInt32,
    pub unk_0x12C: SceUInt32,
}
pub type SceKernelSpinlock = crate::ctypes::c_int;
pub type SceKernelRWSpinlock = crate::ctypes::c_int;
pub type SceKernelIntrStatus = crate::ctypes::c_int;
