/* automatically generated by rust-bindgen 0.58.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

extern "C" {
    pub fn ksceUsbSerialStart() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceUsbSerialSetup(unk: crate::ctypes::c_int) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceUsbSerialStatus() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceUsbSerialClose() -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceUsbSerialGetRecvBufferSize() -> crate::ctypes::c_uint;
}
extern "C" {
    pub fn ksceUsbSerialSend(
        buffer: *const crate::ctypes::c_void,
        len: SceSize,
        unk1: crate::ctypes::c_int,
        unk2: crate::ctypes::c_int,
    ) -> SceSize;
}
extern "C" {
    pub fn ksceUsbSerialRecv(
        buffer: *mut crate::ctypes::c_void,
        max_len: SceSize,
        unk1: crate::ctypes::c_int,
        unk2: crate::ctypes::c_int,
    ) -> SceSize;
}
