/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

extern "C" {
    pub fn ksceKernelSetGPO(gpo: SceUInt32);
}
extern "C" {
    pub fn ksceKernelGetGPO() -> SceUInt32;
}
extern "C" {
    pub fn ksceKernelSetGPI(gpi: SceUInt32);
}
extern "C" {
    pub fn ksceKernelGetGPI() -> SceUInt32;
}
extern "C" {
    pub fn ksceDebugLedRegisterHandle0(
        func: ::core::option::Option<
            unsafe extern "C" fn(
                a1: crate::ctypes::c_int,
                a2: crate::ctypes::c_int,
                a3: crate::ctypes::c_int,
                a4: crate::ctypes::c_int,
            ),
        >,
    );
}
extern "C" {
    pub fn ksceDebugLedInvokeHandle0(
        a1: crate::ctypes::c_int,
        a2: crate::ctypes::c_int,
        a3: crate::ctypes::c_int,
        a4: crate::ctypes::c_int,
    );
}
extern "C" {
    pub fn ksceDebugLedRegisterHandle1(
        func: ::core::option::Option<
            unsafe extern "C" fn(
                a1: crate::ctypes::c_int,
                a2: crate::ctypes::c_int,
                a3: crate::ctypes::c_int,
                a4: crate::ctypes::c_int,
            ),
        >,
    );
}
extern "C" {
    pub fn ksceDebugLedInvokeHandle1(
        a1: crate::ctypes::c_int,
        a2: crate::ctypes::c_int,
        a3: crate::ctypes::c_int,
        a4: crate::ctypes::c_int,
    );
}
