/* automatically generated by rust-bindgen 0.58.1 */

pub mod SceExcpKind {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_EXCP_RESET: Type = 0;
    pub const SCE_EXCP_UNDEF_INSTRUCTION: Type = 1;
    pub const SCE_EXCP_SVC: Type = 2;
    pub const SCE_EXCP_PABT: Type = 3;
    pub const SCE_EXCP_DABT: Type = 4;
    pub const SCE_EXCP_UNUSED: Type = 5;
    pub const SCE_EXCP_IRQ: Type = 6;
    pub const SCE_EXCP_FIQ: Type = 7;
}
extern "C" {
    pub fn ksceExcpmgrGetData() -> *mut crate::ctypes::c_void;
}
extern "C" {
    pub fn ksceExcpmgrRegisterHandler(
        kind: SceExcpKind::Type,
        priority: crate::ctypes::c_int,
        handler: *mut crate::ctypes::c_void,
    ) -> crate::ctypes::c_int;
}
