/* automatically generated by rust-bindgen 0.68.1 */

#[allow(unused_imports)]
use crate::psp2common::kernel::msif::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;

extern "C" {
    pub fn ksceMsifGetMsInfo(info: *mut SceMsInfo) -> crate::ctypes::c_int;
}
