/* automatically generated by rust-bindgen 0.58.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

pub type SceSysEventHandler = ::core::option::Option<
    unsafe extern "C" fn(
        resume: crate::ctypes::c_int,
        eventid: crate::ctypes::c_int,
        args: *mut crate::ctypes::c_void,
        opt: *mut crate::ctypes::c_void,
    ) -> crate::ctypes::c_int,
>;
pub mod SceKernelPowerTickType {
    pub type Type = crate::ctypes::c_uint;
    pub const SCE_KERNEL_POWER_TICK_DEFAULT: Type = 0;
    pub const SCE_KERNEL_POWER_TICK_DISABLE_AUTO_SUSPEND: Type = 1;
    pub const SCE_KERNEL_POWER_TICK_DISABLE_OLED_OFF: Type = 4;
    pub const SCE_KERNEL_POWER_TICK_DISABLE_OLED_DIMMING: Type = 6;
}
extern "C" {
    pub fn ksceKernelPowerTick(type_: crate::ctypes::c_int) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceKernelRegisterSysEventHandler(
        name: *const crate::ctypes::c_char,
        handler: SceSysEventHandler,
        args: *mut crate::ctypes::c_void,
    ) -> crate::ctypes::c_int;
}
