/* automatically generated by rust-bindgen 0.68.1 */

#[allow(unused_imports)]
use crate::psp2common::kernel::threadmgr::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::kernel::threadmgr::lw_mutex::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;
#[allow(unused_imports)]
use crate::vitasdk::build_utils::*;

#[repr(C)]
pub struct SceKernelLwCondInfo {
    pub size: SceSize,
    pub lwcond_id: SceUID,
    pub name: [crate::ctypes::c_char; 32usize],
    pub attr: crate::ctypes::c_int,
    pub work: *mut SceKernelLwCondWork,
    pub lwmutex: *mut SceKernelLwMutexWork,
    pub num_wait_threads: crate::ctypes::c_int,
}
extern "C" {
    pub fn ksceKernelGetLwCondInfo(
        lwcond_id: SceUID,
        info: *mut SceKernelLwCondInfo,
    ) -> crate::ctypes::c_int;
}
