/* automatically generated by rust-bindgen 0.68.1 */

#[allow(unused_imports)]
use crate::psp2common::kernel::threadmgr::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;
#[allow(unused_imports)]
use crate::vitasdk::build_utils::*;

#[repr(C)]
pub struct SceKernelLwMutexInfo {
    pub size: SceSize,
    pub mtxid: SceUID,
    pub name: [crate::ctypes::c_char; 32usize],
    pub attr: crate::ctypes::c_int,
    pub work: *mut SceKernelLwMutexWork,
    pub init_count: crate::ctypes::c_int,
    pub current_count: crate::ctypes::c_int,
    pub current_owner_id: SceUID,
    pub num_wait_threads: SceUInt32,
}
extern "C" {
    pub fn ksceKernelGetLwMutexInfo(
        lwmtxid: SceUID,
        info: *mut SceKernelLwMutexInfo,
    ) -> crate::ctypes::c_int;
}
