/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2common::types::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

pub type SceKernelWorkQueueWorkFunction = ::core::option::Option<
    unsafe extern "C" fn(args: *mut crate::ctypes::c_void) -> crate::ctypes::c_int,
>;
extern "C" {
    pub fn ksceKernelEnqueueWorkQueue(
        uid: SceUID,
        name: *const crate::ctypes::c_char,
        work: SceKernelWorkQueueWorkFunction,
        args: *mut crate::ctypes::c_void,
    ) -> crate::ctypes::c_int;
}
