/* automatically generated by rust-bindgen 0.58.1 */

#[allow(unused_imports)]
use crate::psp2::types::*;
#[allow(unused_imports)]
use crate::psp2kern::io::stat::*;
#[allow(unused_imports)]
use crate::psp2kern::types::*;

#[repr(C)]
pub struct SceIoDirent {
    pub d_stat: SceIoStat,
    pub d_name: [crate::ctypes::c_char; 256usize],
    pub d_private: *mut crate::ctypes::c_void,
    pub dummy: crate::ctypes::c_int,
}
extern "C" {
    pub fn ksceIoDopen(dirname: *const crate::ctypes::c_char) -> SceUID;
}
extern "C" {
    pub fn ksceIoDread(fd: SceUID, dir: *mut SceIoDirent) -> crate::ctypes::c_int;
}
extern "C" {
    pub fn ksceIoDclose(fd: SceUID) -> crate::ctypes::c_int;
}
