pub mod graphics;
pub mod misc;
pub mod stdc;
/* automatically generated by rust-bindgen 0.65.1 */

#[allow(unused_imports)]
use crate::psp2::paf::graphics::*;
#[allow(unused_imports)]
use crate::psp2::paf::misc::*;
#[allow(unused_imports)]
use crate::psp2::paf::stdc::*;
#[allow(unused_imports)]
use crate::psp2common::types::*;
